title: Uncle 404
description: Uncle 404
author: Uncle 404
github: https://github.com/uncle404
about: If not me,who? If not now,when?
avatar_url: /static/img/avatar.jpg

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-github
      link: "https://github.com/uncle404"
    - icon: fa-linkedin
      link: http://www.linkedin.com/in/%E5%91%A8%E6%AF%85-%E4%BD%95-73053b100/
    - icon: fa-rss
      link: /feed.xml

urls:
    - text: 归档
      url: /archives
    - text: 关于
      url: /about/


url: "https://uncle404.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
